from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


PROJECT_DIRS = ("papers", "papers/inbox", "papers/pdfs", "reports", "state", "logs", "traces", "evidence")

DEFAULT_CONFIG: dict[str, Any] = {
    "language": "zh",
    "max_results_per_query": 5,
    "domain_keywords": [
        "embodied intelligence",
        "world model",
        "world action model",
        "WAM",
        "CILD",
        "robot learning",
        "robot manipulation",
        "differentiable simulation",
        "model-based reinforcement learning",
        "representation learning",
    ],
    "search_sources": ["arxiv", "openalex", "semantic_scholar"],
    "evidence_qa": {
        "enabled": True,
        "backend": "paperqa2",
        "max_papers": 8,
        "max_claims": 8,
        "require_pdf": True,
        "mock": False,
    },
    "model_tiers": {
        "cheap": {
            "provider": "gpt_compatible",
            "base_url_env": "GPT_API_BASE_URL",
            "api_key_env": "GPT_API_KEY",
            "base_url": "",
            "api_key": "",
            "model": "deepseek-chat",
            "reasoning_effort": "low",
        },
        "standard": {
            "provider": "gpt_compatible",
            "base_url_env": "GPT_API_BASE_URL",
            "api_key_env": "GPT_API_KEY",
            "base_url": "",
            "api_key": "",
            "model": "gpt-5.4",
            "reasoning_effort": "standard",
        },
        "strong": {
            "provider": "gpt_compatible",
            "base_url_env": "GPT_API_BASE_URL",
            "api_key_env": "GPT_API_KEY",
            "base_url": "",
            "api_key": "",
            "model": "gpt-5.5",
            "reasoning_effort": "high",
        },
        "frontier": {
            "provider": "gpt_compatible",
            "base_url_env": "GPT_API_BASE_URL",
            "api_key_env": "GPT_API_KEY",
            "base_url": "",
            "api_key": "",
            "model": "gpt-5.5",
            "reasoning_effort": "xhigh",
        },
    },
}

SEED_TEMPLATE = """# 原始想法

在这里写一个很不成熟的科研想法。可以很粗糙，但最好包含：

- 你想解决的问题
- 你隐约觉得可行的方法
- 目标任务或实验环境
- 你担心已经有人做过的部分
- 你希望工具重点帮你查的点
"""

SECRETS_TEMPLATE = """# Copy this file to secrets.local.yaml and fill real keys.
# secrets.local.yaml is ignored by git.

model_tiers:
  cheap:
    # DeepSeek official OpenAI-compatible endpoint.
    base_url: https://api.deepseek.com/v1
    api_key: sk-your-deepseek-key

  standard:
    # GPT-compatible relay endpoint, e.g. https://your-relay.example.com/v1
    base_url: https://your-gpt-relay.example.com/v1
    api_key: your-relay-key

  strong:
    base_url: https://your-gpt-relay.example.com/v1
    api_key: your-relay-key

  frontier:
    base_url: https://your-gpt-relay.example.com/v1
    api_key: your-relay-key
"""

GITIGNORE_TEMPLATE = """# Local credentials for idea-workbench
secrets.local.yaml

# Generated run artifacts
traces/
logs/
state/
papers/api_papers.json
reports/
evidence/
"""


@dataclass(frozen=True)
class IdeaProject:
    root: Path
    seed_path: Path
    config_path: Path
    secrets_path: Path
    secrets_example_path: Path
    queries_path: Path
    papers_dir: Path
    evidence_dir: Path
    reports_dir: Path
    state_dir: Path
    logs_dir: Path
    traces_dir: Path


def get_project(root: str | Path) -> IdeaProject:
    project_root = Path(root).expanduser().resolve()
    return IdeaProject(
        root=project_root,
        seed_path=project_root / "seed.md",
        config_path=project_root / "config.yaml",
        secrets_path=project_root / "secrets.local.yaml",
        secrets_example_path=project_root / "secrets.local.yaml.example",
        queries_path=project_root / "queries.yaml",
        papers_dir=project_root / "papers",
        evidence_dir=project_root / "evidence",
        reports_dir=project_root / "reports",
        state_dir=project_root / "state",
        logs_dir=project_root / "logs",
        traces_dir=project_root / "traces",
    )


def init_project(root: str | Path, *, force: bool = False) -> IdeaProject:
    project = get_project(root)
    project.root.mkdir(parents=True, exist_ok=True)
    for dirname in PROJECT_DIRS:
        (project.root / dirname).mkdir(exist_ok=True)

    write_if_missing(project.seed_path, SEED_TEMPLATE, force=force)
    write_if_missing(project.config_path, dump_simple_yaml(DEFAULT_CONFIG), force=force)
    write_if_missing(project.secrets_example_path, SECRETS_TEMPLATE, force=force)
    write_if_missing(project.root / ".gitignore", GITIGNORE_TEMPLATE, force=force)
    write_if_missing(project.queries_path, "# search queries will be generated by `idea-workbench search`\n", force=force)
    return project


def assert_project(root: str | Path) -> IdeaProject:
    project = get_project(root)
    missing = [path for path in (project.seed_path, project.config_path) if not path.exists()]
    if missing:
        names = ", ".join(str(path) for path in missing)
        raise FileNotFoundError(f"not an idea-workbench project, missing: {names}")
    for dirname in PROJECT_DIRS:
        (project.root / dirname).mkdir(exist_ok=True)
    return project


def write_if_missing(path: Path, text: str, *, force: bool = False) -> None:
    if path.exists() and not force:
        return
    path.write_text(text, encoding="utf-8")


def read_text(path: Path, default: str = "") -> str:
    if not path.exists():
        return default
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def detail_report_path(project: IdeaProject, filename: str) -> Path:
    return project.reports_dir / "details" / filename


def read_detail_report(project: IdeaProject, filename: str) -> str:
    detail = detail_report_path(project, filename)
    if detail.exists():
        return read_text(detail)
    return read_text(project.reports_dir / filename)


def load_config(project: IdeaProject) -> dict[str, Any]:
    parsed = parse_simple_yaml(read_text(project.config_path))
    secrets = parse_simple_yaml(read_text(project.secrets_path))
    config = deep_merge(DEFAULT_CONFIG, parsed)
    config = deep_merge(config, secrets)
    return config


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged: dict[str, Any] = {}
    for key, value in base.items():
        if isinstance(value, dict):
            merged[key] = deep_merge(value, {})
        elif isinstance(value, list):
            merged[key] = list(value)
        else:
            merged[key] = value
    for key, value in override.items():
        if value in ("", None):
            continue
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def dump_simple_yaml(data: dict[str, Any], *, indent: int = 0) -> str:
    lines: list[str] = []
    for key, value in data.items():
        prefix = " " * indent
        if isinstance(value, dict):
            lines.append(f"{prefix}{key}:")
            nested = dump_simple_yaml(value, indent=indent + 2).rstrip()
            if nested:
                lines.append(nested)
        elif isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            for item in value:
                lines.append(f"{prefix}  - {item}")
        else:
            lines.append(f"{prefix}{key}: {value}")
    return "\n".join(lines) + "\n"


def parse_simple_yaml(text: str) -> dict[str, Any]:
    """Parse the small YAML subset used by this tool.

    Supported forms are nested dictionaries, scalar lines (`key: value`), and
    scalar lists. This is not a full YAML parser; it is deliberately limited so
    the CLI can run without PyYAML.
    """

    raw_lines = [
        line.rstrip()
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    root: dict[str, Any] = {}
    stack: list[tuple[int, dict[str, Any] | list[Any]]] = [(-1, root)]

    for index, raw_line in enumerate(raw_lines):
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        stripped = raw_line.strip()
        while stack and indent <= stack[-1][0]:
            stack.pop()
        parent = stack[-1][1]

        if stripped.startswith("- "):
            if isinstance(parent, list):
                parent.append(parse_scalar(stripped[2:].strip()))
            continue

        if ":" not in stripped or not isinstance(parent, dict):
            continue

        key, value = stripped.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value:
            parent[key] = parse_scalar(value)
            continue

        next_line = next_nonempty_line(raw_lines, index + 1)
        child: dict[str, Any] | list[Any]
        if next_line and next_line.strip().startswith("- "):
            child = []
        else:
            child = {}
        parent[key] = child
        stack.append((indent, child))

    return root


def next_nonempty_line(lines: list[str], start: int) -> str | None:
    for line in lines[start:]:
        if line.strip() and not line.lstrip().startswith("#"):
            return line
    return None


def parse_scalar(value: str) -> Any:
    lowered = value.lower()
    if lowered in {"true", "false"}:
        return lowered == "true"
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        pass
    return value.strip("\"'")
